default:
  image: znck/docker-pnpm
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .pnpm-store/
      - node_modules/
  before_script:
    - npm config set store ./.pnpm-store
    - pnpm store prune
    - pnpm install

stages:
  - lint
  - test
  - build

lint:
  stage: lint
  script:
    - pnpm run lint

test:
  stage: test
  script:
    - pnpm run test

build:
  stage: build
  script:
    - pnpm run build
